name: windows-arm64 build

inputs:
  vvv:
    required: true
    description: "Qt long version"
  vv:
    required: true
    description: "Qt short version"
  comp:
    required: true
    description: "Compiler, e.g. msvc2022"
  archive:
    required: true
    description: "Archive name"
  link:
    required: true
    description: "Link to compiler binary archive"
outputs:
  fn:
    description: "Filename"
    value: ${{steps.build.outputs.fn}}
  path:
    description: "Path"
    value: ${{steps.build.outputs.path}}

runs:
  using: composite
  steps:
    - id: build
      shell: powershell
      run: |
        Remove-Item C:\mingw64 -Recurse -Force -ErrorAction SilentlyContinue
        Start-BitsTransfer -Source ${{inputs.link}}${{inputs.archive}} -Destination .
        $folder = (7z l .\${{inputs.archive}} -ba `
          | Select-String '(?<=\s)([^\s\\]+)(?=\\)' `
          | Select-Object -First 1).Matches[0].Groups[1].Value
        7z x .\${{inputs.archive}} -o"C:\"
        Rename-Item -Path "C:\$folder" -NewName "mingw64" -ErrorAction SilentlyContinue
        choco install ninja -f -y
        Start-BitsTransfer -Source `
          "https://download.qt.io/archive/qt/${{inputs.vv}}/${{inputs.vvv}}/single/qt-everywhere-src-${{inputs.vvv}}.zip" `
          -Destination .
        7z x .\qt-everywhere-src-${{inputs.vvv}}.zip -o"./"
        Rename-Item -Path "qt-everywhere-src-${{inputs.vvv}}" -NewName "qt"
        mkdir qt\build
        cd qt\build
        ..\configure.bat `
          -prefix ".\qt${{inputs.vvv}}_static_windows_${{inputs.comp}}_x64" `
          -release `
          -static `
          -opensource `
          -confirm-license `
          -nomake examples `
          -nomake tests `
          -- `
          -DCMAKE_C_COMPILER="gcc.exe" -DCMAKE_CXX_COMPILER="g++.exe" -G"Ninja"
        cmake --build . --parallel $env:NUMBER_OF_PROCESSORS
        cmake --install .
        7z a -tzip `
          ".\qt${{inputs.vvv}}_static_windows_${{inputs.comp}}_x64.zip" `
          ".\qt${{inputs.vvv}}_static_windows_${{inputs.comp}}_x64\*"
        Add-Content -Path $env:GITHUB_OUTPUT -Value `
          "fn=qt${{inputs.vvv}}_static_windows_${{inputs.comp}}_x64.zip"
        Add-Content -Path $env:GITHUB_OUTPUT -Value `
          "path=qt/build/qt${{inputs.vvv}}_static_windows_${{inputs.comp}}_x64.zip"
