name: unix build

inputs:
  version:
    required: true
    description: "Qt long version"
outputs:
  fn:
    description: "Filename"
    value: ${{steps.build.outputs.fn}}
  path:
    description: "Path"
    value: ${{steps.build.outputs.path}}

runs:
  using: composite
  steps:
    - name: deps
      shell: bash
      run: |
        brew install boost freetype gettext glib jpeg-turbo libpng libtiff \
          make md4c pcre2 pkgconf sqlite webp zstd
    - name: env
      shell: bash
      run: |
        v='${{inputs.version}}'
        vv="${v%.*}"
        arch=$(uname -m)
        echo "v=$v" >> $GITHUB_ENV
        echo "vv=$vv" >> $GITHUB_ENV
        echo "arch=$arch" >> $GITHUB_ENV
    - name: Cache Qt source archive
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: qt-everywhere-opensource-src-${{env.v}}.tar.xz
        key: qt-everywhere-opensource-src-${{env.v}}.tar.xz
    - name: download
      if: steps.cache-qt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q "https://download.qt.io/archive/qt/${{env.vv}}/${{env.v}}/single/qt-everywhere-opensource-src-${{env.v}}.tar.xz"
    - name: unpack
      shell: bash
      run: |
        tar -xf "qt-everywhere-opensource-src-${{env.v}}.tar.xz"
        mv "qt-everywhere-src-${{env.v}}" qt
        mkdir qt/build
    - name: patch
      shell: bash
      run: |
        prefix=$(brew --prefix)
        rm -rf qt/qtlocation/src/3rdparty/mapbox-gl-native/deps/boost/1.65.1/include/boost
        ln -s $prefix/opt/boost/include/boost \
          qt/qtlocation/src/3rdparty/mapbox-gl-native/deps/boost/1.65.1/include
        cp patches/qt5/936486.diff qt/qtlocation
        cd ${{github.workspace}}/qt/qtlocation
        patch < 936486.diff
    - id: build
      shell: bash
      run: |
        cd qt/build
        ../configure \
          -prefix "./qt${{env.v}}_static_macos_${{env.arch}}" \
          -release \
          -static \
          -opensource \
          -confirm-license \
          -nomake examples \
          -nomake tests \
          -skip qtwebengine \
          QMAKE_APPLE_DEVICE_ARCHS=${{env.arch}}
        gmake -j$(sysctl -n hw.ncpu)
        gmake install
        tar -czf "qt${{env.v}}_static_macos_${{env.arch}}.tar.gz" "qt${{env.v}}_static_macos_${{env.arch}}"
        echo "fn=qt${{env.v}}_static_macos_${{env.arch}}.tar.gz" >> $GITHUB_OUTPUT
        echo "path=$(realpath "qt${{env.v}}_static_macos_${{env.arch}}.tar.gz")" >> $GITHUB_OUTPUT
